# Generated by Django 4.1.4 on 2022-12-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='image',
        ),
    ]
